version: 0.2

phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Image Tag: $IMAGE_TAG"
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 468917192189.dkr.ecr.ap-northeast-2.amazonaws.com
  
  build:
    command:
      - docker build -t 468917192189.dkr.ecr.ap-northeast-2.amazonaws.com/villanono-backend:$IMAGE_TAG .
      - docker push 468917192189.dkr.ecr.ap-northeast-2.amazonaws.com/villanono-backend:$IMAGE_TAG
