services:
  villanono-backend:
    image: 468917192189.dkr.ecr.ap-northeast-2.amazonaws.com/villanono-backend:250504-02
    container_name: villanono-backend
    ports:
      - 5000:5000
    environment:
      - ElasticSearch.URL=https://opensearch-node1:9200
    networks:
      - villanono-backend
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-dev-node
    environment:
      - discovery.type=single-node
      # OPENSEARCH_INITIAL_ADMIN_PASSWORD 환경 변수는 데모 설정 비활성화 시 필요
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ZhPRy1o3hjVkaDHwG60F
    volumes:
      # - C:/Github/villanono-backend/.taskdefinition/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-data1:/usr/share/opensearch/data # 데이터 볼륨 유지
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - villanono-backend
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - "OPENSEARCH_HOSTS=https://opensearch-node1:9200"
    networks:
      - villanono-backend
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data1:


networks:
  villanono-backend:
